baseURL: https://qeubar.github.io
languageCode: en-us
title: qeubar blog
theme: mini

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

# googleAnalytics: your-google-analytics-id
# disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: vim


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  github: github.com/qeubar


# Site parameters
params:
  # Site Author
  author: Bardia Keyoumarsi
  # Author biography
  bio: Software Bluh Bluh Bluh
  # Site Description, used in HTML meat
  description: A place for some bluh bluh bluh
  enableRSS: false
  # To enable comments, you may need to set `disqusShortname`
  # enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  # enableGoogleAnalytics: true

  # Optional
  home: '' # Default: Home
  about: '' # Default: About
  archive: '' # Default: Archive
  tags: '' # Default: Tags
  subscribe: '' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  copyright: '' # Default: © Copyright 2021 ❤️ author
  title404: '' # Default: 404 - Page Not Found
  subtitle404: '' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
